// packages/in-devtools-tui/src/panes/RecordsPane.tsx
import React from 'react'
import { Box, Text } from 'ink'
import type { RecordPage, InspectorCollection } from '@noy-db/in-devtools'

const MASK = '••••'

function cell(value: unknown): string {
  if (value === null || value === undefined) return '·'
  if (typeof value === 'object') return Array.isArray(value) ? `[${(value as unknown[]).length}]` : '{…}'
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value)
  return '?'
}

export function RecordsPane({ collection, page, error, revealAll }: {
  collection: InspectorCollection
  page: RecordPage | null
  error?: string
  revealAll?: boolean
}) {
  // Build the set of sensitive field keys from described[] (pii + secret); empty if no described.
  const sensitiveKeys: ReadonlySet<string> = React.useMemo(() => {
    if (!collection.described) return new Set<string>()
    const keys = new Set<string>()
    for (const f of collection.described) {
      if (f.sensitivity !== undefined && f.sensitivity !== 'public') keys.add(f.key)
    }
    return keys
  }, [collection.described])

  const schemaFields = Object.keys(collection.fields)
  if (error) return <Box flexDirection="column"><Text color="red">records error: {error}</Text><Text dimColor>n/p retry · ⇥ back</Text></Box>
  if (!page) return <Box flexDirection="column"><Text dimColor>loading records…</Text></Box>
  // Fall back to first-row keys when schema has no declared fields
  const firstRowKeys = page.rows.length > 0 && typeof page.rows[0] === 'object' && page.rows[0] !== null
    ? Object.keys(page.rows[0] as Record<string, unknown>)
    : []
  const fields = schemaFields.length > 0 ? schemaFields : firstRowKeys
  const from = page.total === 0 ? 0 : page.offset + 1
  const to = Math.min(page.offset + page.limit, page.total)

  function renderCell(f: string, row: unknown): string {
    const raw = cell((row as Record<string, unknown>)?.[f])
    if (!revealAll && sensitiveKeys.has(f)) return MASK
    return raw
  }

  const revealHint = sensitiveKeys.size > 0 ? ' · r reveal/hide' : ''
  return (
    <Box flexDirection="column">
      <Text bold>rows {from}–{to} of {page.total} <Text dimColor>(n/p page · ⇥ back{revealHint})</Text></Text>
      <Text dimColor>{fields.join('  ')}</Text>
      {page.rows.map((row, i) => (
        <Text key={i}>{fields.map((f) => renderCell(f, row)).join('  ')}</Text>
      ))}
    </Box>
  )
}

// packages/in/in-nuxt/src/runtime/devtools/panes/RecordsPane.vue
<template>
  <div class="noydb-records">
    <div class="noydb-records__header">
      <template v-if="page">
        rows
        <strong>{{ page.total === 0 ? 0 : page.offset + 1 }}–{{ Math.min(page.offset + page.limit, page.total) }}</strong>
        of <strong>{{ page.total }}</strong>
      </template>
      <span v-else-if="error" class="noydb-records__error">{{ error }}</span>
      <span v-else class="noydb-records__loading">loading…</span>
      <div class="noydb-records__nav">
        <button :disabled="!canPrev" @click="$emit('prev')">◀ prev</button>
        <button :disabled="!canNext" @click="$emit('next')">next ▶</button>
      </div>
      <button
        v-if="hasSensitiveFields"
        class="noydb-records__reveal-all"
        data-reveal-all
        @click="revealAll = !revealAll"
      >{{ revealAll ? 'hide all' : 'reveal all' }}</button>
    </div>
    <template v-if="page && fields.length > 0">
      <div class="noydb-records__cols">
        <span v-for="f in fields" :key="f">{{ f }}</span>
      </div>
      <div v-if="page.rows.length === 0" class="noydb-records__empty">No records</div>
      <div v-for="(row, i) in page.rows" :key="i" class="noydb-records__row">
        <span v-for="f in fields" :key="f">
          <template v-if="isVisible(f)">{{ cell(row, f) }}</template>
          <button
            v-else
            class="noydb-records__mask"
            :data-reveal="f"
            @click="reveal(f)"
          >••••</button>
        </span>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { InspectorCollection, RecordPage } from '@noy-db/in-devtools'

const props = defineProps<{
  collection: InspectorCollection
  page: RecordPage | null
  error: string | undefined
}>()

defineEmits<{ prev: []; next: [] }>()

const fields = computed(() => Object.keys(props.collection.fields))

const canPrev = computed(() => !!props.page && props.page.offset > 0)
const canNext = computed(() => !!props.page && props.page.offset + props.page.limit < props.page.total)

// ── PII masking ────────────────────────────────────────────────────────────

/** Set of field keys that are sensitive (pii or secret) per collection.described. */
const sensitiveFields = computed((): Set<string> => {
  const described = props.collection.described
  if (!described) return new Set()
  const s = new Set<string>()
  for (const d of described) {
    if (d.sensitivity !== undefined && d.sensitivity !== 'public') {
      s.add(d.key)
    }
  }
  return s
})

const hasSensitiveFields = computed(() => sensitiveFields.value.size > 0)

/** Tracks which individual fields the user has revealed. */
const revealed = ref(new Set<string>())

/** When true, all sensitive fields are shown. */
const revealAll = ref(false)

// Reset reveal state when the viewed collection changes (prevent PII from one
// collection lingering when the user navigates to another).
watch(() => props.collection, () => { revealed.value = new Set(); revealAll.value = false })

function isVisible(field: string): boolean {
  if (!sensitiveFields.value.has(field)) return true
  if (revealAll.value) return true
  return revealed.value.has(field)
}

function reveal(field: string): void {
  revealed.value = new Set([...revealed.value, field])
}

function cell(row: unknown, field: string): string {
  if (row === null || row === undefined || typeof row !== 'object') return '·'
  const val = (row as Record<string, unknown>)[field]
  if (val === null || val === undefined) return '·'
  if (typeof val === 'object') return Array.isArray(val) ? `[${(val as unknown[]).length}]` : '{…}'
  return String(val)
}
</script>
