// packages/in-devtools-tui/src/panes/RecordsPane.tsx
import React from 'react'
import { Box, Text } from 'ink'
import type { RecordPage, InspectorCollection } from '@noy-db/in-devtools'

function cell(value: unknown): string {
  if (value === null || value === undefined) return '·'
  if (typeof value === 'object') return Array.isArray(value) ? `[${(value as unknown[]).length}]` : '{…}'
  if (typeof value === 'string') return value
  if (typeof value === 'number' || typeof value === 'boolean' || typeof value === 'bigint') return String(value)
  return '?'
}

export function RecordsPane({ collection, page, error }: {
  collection: InspectorCollection
  page: RecordPage | null
  error?: string
}) {
  const schemaFields = Object.keys(collection.fields)
  if (error) return <Box flexDirection="column"><Text color="red">records error: {error}</Text><Text dimColor>n/p retry · ⇥ back</Text></Box>
  if (!page) return <Box flexDirection="column"><Text dimColor>loading records…</Text></Box>
  // Fall back to first-row keys when schema has no declared fields
  const firstRowKeys = page.rows.length > 0 && typeof page.rows[0] === 'object' && page.rows[0] !== null
    ? Object.keys(page.rows[0] as Record<string, unknown>)
    : []
  const fields = schemaFields.length > 0 ? schemaFields : firstRowKeys
  const from = page.total === 0 ? 0 : page.offset + 1
  const to = Math.min(page.offset + page.limit, page.total)
  return (
    <Box flexDirection="column">
      <Text bold>rows {from}–{to} of {page.total} <Text dimColor>(n/p page · ⇥ back)</Text></Text>
      <Text dimColor>{fields.join('  ')}</Text>
      {page.rows.map((row, i) => (
        <Text key={i}>{fields.map((f) => cell((row as Record<string, unknown>)?.[f])).join('  ')}</Text>
      ))}
    </Box>
  )
}

// packages/in-nuxt/src/runtime/devtools/panes/RecordsPane.vue
<template>
  <div class="noydb-records">
    <div class="noydb-records__header">
      <template v-if="page">
        rows
        <strong>{{ page.total === 0 ? 0 : page.offset + 1 }}–{{ Math.min(page.offset + page.limit, page.total) }}</strong>
        of <strong>{{ page.total }}</strong>
      </template>
      <span v-else-if="error" class="noydb-records__error">{{ error }}</span>
      <span v-else class="noydb-records__loading">loading…</span>
      <div class="noydb-records__nav">
        <button :disabled="!canPrev" @click="$emit('prev')">◀ prev</button>
        <button :disabled="!canNext" @click="$emit('next')">next ▶</button>
      </div>
    </div>
    <template v-if="page && fields.length > 0">
      <div class="noydb-records__cols">
        <span v-for="f in fields" :key="f">{{ f }}</span>
      </div>
      <div v-if="page.rows.length === 0" class="noydb-records__empty">No records</div>
      <div v-for="(row, i) in page.rows" :key="i" class="noydb-records__row">
        <span v-for="f in fields" :key="f">{{ cell(row, f) }}</span>
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { InspectorCollection, RecordPage } from '@noy-db/in-devtools'

const props = defineProps<{
  collection: InspectorCollection
  page: RecordPage | null
  error: string | undefined
}>()

defineEmits<{ prev: []; next: [] }>()

const fields = computed(() => Object.keys(props.collection.fields))

const canPrev = computed(() => !!props.page && props.page.offset > 0)
const canNext = computed(() => !!props.page && props.page.offset + props.page.limit < props.page.total)

function cell(row: unknown, field: string): string {
  if (row === null || row === undefined || typeof row !== 'object') return '·'
  const val = (row as Record<string, unknown>)[field]
  if (val === null || val === undefined) return '·'
  if (typeof val === 'object') return Array.isArray(val) ? `[${(val as unknown[]).length}]` : '{…}'
  return String(val)
}
</script>
