// packages/in-nuxt/src/runtime/devtools/panes/WriteMonitor.vue
<template>
  <div class="noydb-monitor">
    <div v-if="meter" class="noydb-monitor__latency">
      put p50 {{ meter.byMethod?.['put']?.p50 ?? '—' }}ms
      p99 {{ meter.byMethod?.['put']?.p99 ?? '—' }}ms
      · del p50 {{ meter.byMethod?.['delete']?.p50 ?? '—' }}ms
      <span v-if="meter.status === 'degraded'" class="noydb-monitor__degraded"> ⚠ degraded</span>
    </div>
    <div class="noydb-monitor__cols">
      <span>time</span>
      <span>user</span>
      <span>op</span>
      <span>target</span>
      <span>ver</span>
    </div>
    <div v-if="rows.length === 0" class="noydb-monitor__empty">Waiting for writes…</div>
    <div
      v-for="(row, i) in rows"
      :key="i"
      :class="['noydb-monitor__row', { 'noydb-monitor__row--conflict': row.conflict }]"
    >
      <span>{{ row.time }}</span>
      <span>{{ row.user }}</span>
      <span>{{ row.op }}</span>
      <span>{{ row.target }}</span>
      <span>{{ row.versions }}</span>
      <span v-if="row.conflict" class="noydb-monitor__badge">⚠ conflict</span>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { MeterSnapshot } from '@noy-db/to-meter'

export interface FeedRow {
  readonly time: string
  readonly user: string
  readonly op: 'put' | 'del'
  readonly target: string
  readonly versions: string
  readonly baseKey: string
  conflict: boolean
}

defineProps<{
  rows: ReadonlyArray<FeedRow>
  meter: MeterSnapshot | null
}>()
</script>

// packages/in-devtools-tui/src/panes/WriteMonitor.tsx
import React from 'react'
import { Box, Text } from 'ink'
import type { FeedRow } from '../types.js'
import type { MeterSnapshot } from '@noy-db/to-meter'

export function WriteMonitor({ vaultName, rows, meter }: { vaultName: string; rows: ReadonlyArray<FeedRow>; meter: MeterSnapshot | null }) {
  const m = meter?.byMethod
  return (
    <Box flexDirection="column">
      <Text bold>Write Monitor — {vaultName} <Text dimColor>(w/esc · c clear · q quit)</Text></Text>
      {meter && m && (
        <Text>
          store  put p50 {m.put?.p50 ?? '—'}ms p99 {m.put?.p99 ?? '—'}ms{meter.status === 'degraded' ? ' ⚠degraded' : ''} · del p50 {m.delete?.p50 ?? '—'} p99 {m.delete?.p99 ?? '—'} · get p50 {m.get?.p50 ?? '—'} p99 {m.get?.p99 ?? '—'}
        </Text>
      )}
      <Text dimColor>time      user    op   collection/docId    v</Text>
      {rows.length === 0 && <Text dimColor>(waiting for writes…)</Text>}
      {rows.map((r, i) => (
        r.conflict
          ? <Text key={i} color="yellow">{r.time}  {r.user.padEnd(6)}  {r.op}  {r.target.padEnd(18)} {r.versions}  ⚠ CONFLICT</Text>
          : <Text key={i}>{r.time}  {r.user.padEnd(6)}  {r.op}  {r.target.padEnd(18)} {r.versions}</Text>
      ))}
    </Box>
  )
}
